### ISSUE TITLE
Generate definition file

### ISSUE THREAD

**Issue by kievechua** [flyjs/fly-typescript#4]
Is there anyway to generate definition file using this libraries?
'*.d.ts' file

**Comment by lukeed** [comment]
Yes, as per the [Typescript docs](https://www.typescriptlang.org/docs/handbook/compiler-options.html), you can use the `declaration` option.

**Comment by kievechua** [comment]
Seriously not sure how I miss it, been going through it few time ...
Thanks!

**Comment by lukeed** [comment]
Haha it's pretty easy to miss things in these docs! Can't blame you
